Improvements I think
AmanoTeam/UserLixo pull request #81
Opened 2021-09-19 17:45 UTC by HitaloSama

**About:**
- Heroku support has been removed
- Fixes/improvements in the code
- Simplified code
- Linting with flake8
- Code formatted with black
- Imports reorganized with isort (using black profile)
- Added SPDX-License-Identifier
- Disabled the handler check for plug-ins (not working properly)

2021-09-20 13:02 UTC, AndrielFR approved these changes
hitalo aguenta

2021-09-22 02:30 UTC, usernein requested changes
hitalo aguenta

2021-09-22 02:30 UTC, usernein commented on userlixo/handlers/bot/callback_query/info_plugin.py
>          return await cq.answer(lang.plugin_not_found(name=plugin))
```suggestion

    if basename not in plugins[plugin_type]:
        return await cq.answer(lang.plugin_not_found(name=basename))
    plugin = plugins[plugin_type][basename]
```

2021-09-22 02:30 UTC, usernein commented on userlixo/login.py
```suggestion

    login_bot = True
```

2021-09-22 02:30 UTC, usernein commented on userlixo/login.py
> +        click.getchar(True)
```suggestion
        c = click.getchar(True)
        login_bot = c == "n"
```

2021-09-22 02:30 UTC, usernein commented on userlixo/login.py
> +    if login_user and os.path.exists("bot.session"):
```suggestion
    if login_bot and os.path.exists("bot.session"):
```

2021-09-22 02:30 UTC, usernein commented on userlixo/config.py
> +            missing_vars.append([env_key, value_on_env, env_info])
```suggestion
        if not value_on_db:
            if env_key in restricted_vars:
                os.environ[env_key] = value_on_env
            else:
                missing_vars.append([env_key, value_on_env, env_info])
            continue
```

2021-09-22 12:46 UTC, usernein approved these changes
hitalo parabéns

2021-09-22 12:54 UTC, HitaloSama commented
> hitalo parabéns

Obrigado 😊

2021-09-28 22:28 UTC, alissonlauffer approved these changes
Fix the conflicts, thanks 👍

2021-09-28 22:36 UTC, AndrielFR commented
nice bro.

2021-09-29 18:39 UTC, HitaloSama commented
> Fix the conflicts, thanks 👍

Larga de ser loco

2021-10-05 19:14 UTC, HitaloSama commented
Alô

2021-10-05 20:11 UTC, AndrielFR approved these changes
nice. 👍

2021-10-05 20:18 UTC, alissonlauffer commented
What about https://t.me/SpamTherapy/212931?

2021-10-06 00:44 UTC, HitaloSama commented
> What about https://t.me/SpamTherapy/212931?

It would be a backup branch, just @usernein create before merging this PR.

2021-10-06 00:50 UTC, merged